#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=13G
#SBATCH --time=47:00:00
#SBATCH -p serial_requeue
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=halidaee@gmail.com  

# Set Environmental Variables
# Settings are copied from the rsession.sh generated by OpenOnDemand when launching RStudio Server. 

# First, directories
export LAB_DIR=/n/holylabs/LABS/koning_lab/Users/halidaee
export my_sif=/n/singularity_images/informatics/ifxrstudio/ifxrstudio:RELEASE_3_18.sif
readonly image_tag=$(basename "${my_sif##*:}" .sif)
export my_sif_r_packages=${HOME}/R/ifxrstudio/${image_tag}

# Second, C library options. These should match allocation. 
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
export MKL_THREADING_LAYER=GNU

# Go to the project directory
cd ${LAB_DIR}/debug_help

# Uncomment line below to skip checking whether need to install dependent packages, including nuclear_ard from GitHub. 
singularity exec --cleanenv --env R_LIBS_USER=${my_sif_r_packages} ${my_sif}  Rscript --no-save --no-restore --verbose install_packages.R

# Remove any log files created from prior run of script
rm *debug.log

# Decide which array indices we run the job for. Master set is 1-1200.
# Index from array deterministically defines both job parameters and random seed.   
array=(600 603 716)

# Execute proper_cross_validation_debug.R for each array index. 
for i in "${array[@]}"
do
    singularity exec --cleanenv --env LAB_DIR=${LAB_DIR},OMP_NUM_THREADS=${OMP_NUM_THREADS},MKL_NUM_THREADS=${MKL_NUM_THREADS},MKL_THREADING_LAYER=${MKL_THREADING_LAYER},R_LIBS_USER=${my_sif_r_packages},ARRAY_ID=${i} ${my_sif} Rscript --no-save --no-restore --verbose proper_cv_debug.R > job_array_output_${i}_debug.log 2>&1
done